name: .NET Core

on: [push]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    steps:
    - name: Setup .NET Core if needed
      uses: actions/setup-dotnet@v1.2.0
      with:
        dotnet-version: 3.0.100
      if: matrix.os == 'macOS-latest' || matrix.os == 'ubuntu-latest'
    - uses: actions/checkout@v1
    - name: Build with dotnet
      run: |
        cd Backend/
        dotnet build -c Release
    - uses: actions/checkout@v1
    - name: Test with dotnet
      run: |
        cd Test/Backend.Tests/
        dotnet build -c Release
        dotnet vstest ./bin/Release/netcoreapp3.0/Backend.Tests.dll
