name: .NET Core

on: [push]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    steps:
    - name: Setup .NET Core if needed
      uses: actions/setup-dotnet@v1.2.0
      with:
        dotnet-version: 3.0.100
      if: matrix.os == 'macOS-latest' || matrix.os == 'ubuntu-latest'
    - name: Build with dotnet
      run: |
        ls
        dotnet build ./zetsubou-gacha.sln --configuration Release
    - name: Test with dotnet
      run: dotnet test ./zetsubou-gacha.sln --configuration Release
